`build`では`draft`にせず、タグのプッシュでpublishする

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,12 +1,16 @@
 # 処理の流れ
-# 1. create-draft-release: タグなしでdraft releaseを先に作成
+# 1. 以下の二つを順不同で行う
+#   a. create-draft-release: タグなしでdraft releaseを先に作成
+#   b. （VOICEVOX ONNX Runtimeのみ）利用規約を取得
 # 2. build-onnxruntime等: 各成果物をdraft releaseにアップロード
-# 3. prerelease: 全ビルド成功後に初めてタグを作成し、draftをprereleaseに変更
+# 3. b.と2.の情報からreleaseのbodyを作成
 
 name: Build C++ Shared Library
 
 on:
   push:
+    branches:
+      - '**'
   workflow_dispatch:
     inputs:
       version:
@@ -44,7 +48,16 @@ defaults:
     shell: bash
 
 jobs:
+  config:
+    runs-on: ubuntu-latest
+    outputs:
+      tag: ${{ env.TARGET_LIBRARY }}-${{ env.ONNXRUNTIME_VERSION }}
+    steps:
+      - name: Nop
+        run: ':'
+
   create-draft-release:
+    needs: config
     runs-on: ubuntu-latest
     outputs:
       # `RELEASE`がtrueなら、GitHub REST APIの`Release`オブジェクトの一部。falseならnull。
@@ -53,13 +66,13 @@ jobs:
       - name: Confirm that the tag does not exist at the moment
         if: env.RELEASE == 'true'
         run: |
-          tag=$TARGET_LIBRARY-$ONNXRUNTIME_VERSION
+          tag=${{ needs.config.outputs.tag }}
           exists=$(
             gh api \
               "/repos/$GITHUB_REPOSITORY/git/matching-refs/tags/$tag" \
               -H 'Accept: application/vnd.github+json' \
               -H 'X-GitHub-Api-Version: 2022-11-28' \
-              -q '[.] | flatten | any(.ref == "refs/tags/'"$tag"'")'
+              -q '[.] | flatten | any(.ref == "refs/tags/'$tag'")'
           )
           if [ "$exists" = true ]; then
             echo "::error title=create-draft-release::'refs/tags/$tag' already exists"
@@ -68,22 +81,22 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Create a draft release without real tag
+      - name: Create a tagless draft release
         if: env.RELEASE == 'true'
         id: create-draft-release
         run: |
-          tag=$TARGET_LIBRARY-$ONNXRUNTIME_VERSION
+          name=${{ needs.config.outputs.tag }}
           release=$(
             gh api \
               "/repos/$GITHUB_REPOSITORY/releases" \
               --method POST \
               -H 'Accept: application/vnd.github+json' \
               -H 'X-GitHub-Api-Version: 2022-11-28' \
-              -f "tag_name=$tag" \
+              -f tag_name= \
               -f "target_commitish=$GITHUB_SHA" \
-              -f "name=$tag" \
+              -f name=$name \
               -F draft=true \
-              -q '{ upload_url, id, tag_name }'
+              -q '{ upload_url, id }'
           )
           echo "release=$release" >> "$GITHUB_OUTPUT"
         env:
@@ -846,7 +859,7 @@ jobs:
           path: VOICEVOX_ORT_TERMS.md
 
   build-spec-table:
-    needs: [create-draft-release, build-onnxruntime, build-xcframework, get-terms]
+    needs: [config, create-draft-release, build-onnxruntime, build-xcframework, get-terms]
     runs-on: ubuntu-22.04
     steps:
       - name: Download specifications
@@ -888,7 +901,7 @@ jobs:
             release_notes+="      <td>$(jq .os -r <<< "$specs")</td>"$'\n'
             release_notes+="      <td>$(jq .arch -r <<< "$specs")</td>"$'\n'
             release_notes+="      <td>$(jq .devices -r <<< "$specs")</td>"$'\n'
-            release_notes+="      <td><a href=\"https://github.com/$GITHUB_REPOSITORY/releases/download/$TARGET_LIBRARY-$ONNXRUNTIME_VERSION/$release_name.tgz\">$release_name.tgz</a></td>"$'\n'
+            release_notes+="      <td><a href=\"https://github.com/$GITHUB_REPOSITORY/releases/download/${{ needs.config.outputs.tag }}/$release_name.tgz\">$release_name.tgz</a></td>"$'\n'
             release_notes+=$'    </tr>\n'
           done
           release_notes+=$(
@@ -912,7 +925,7 @@ jobs:
                 <td>iOS</td>
                 <td>AArch64/x86_64</td>
                 <td>CPU</td>
-                <td><a href="https://github.com/$GITHUB_REPOSITORY/releases/download/$TARGET_LIBRARY-$ONNXRUNTIME_VERSION/${{ needs.build-xcframework.outputs.release-name }}.zip">${{ needs.build-xcframework.outputs.release-name }}.zip</a></td>
+                <td><a href="https://github.com/$GITHUB_REPOSITORY/releases/download/${{ needs.config.outputs.tag }}/${{ needs.build-xcframework.outputs.release-name }}.zip">${{ needs.build-xcframework.outputs.release-name }}.zip</a></td>
               </tr>
             </tbody>
           </table>
@@ -938,32 +951,37 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  prerelease:
-    needs: [create-draft-release, build-onnxruntime, build-xcframework, build-spec-table]
-    if: inputs.release
+  set-tag-name:
+    needs: [config, create-draft-release, build-spec-table]
     runs-on: ubuntu-latest
     steps:
-      - name: Create the tag
+      - name: Set the tag name
         run: |
-          tag=${{ fromJson(needs.create-draft-release.outputs.release).tag_name }}
-          gh api \
-            "/repos/$GITHUB_REPOSITORY/git/refs" \
-            --method POST \
-            -H 'Accept: application/vnd.github+json' \
-            -H 'X-GitHub-Api-Version: 2022-11-28' \
-            -f "ref=refs/tags/$tag" \
-            -f "sha=$GITHUB_SHA"
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          tag=${{ needs.config.outputs.tag }}
+          release_id=${{ fromJson(needs.create-draft-release.outputs.release).id }}
+          for _ in {1..5}; do
+            gh api \
+              "/repos/$GITHUB_REPOSITORY/releases/$release_id" \
+              --method PATCH \
+              -H 'Accept: application/vnd.github+json' \
+              -H 'X-GitHub-Api-Version: 2022-11-28' \
+              -f tag_name=$tag
 
-      - name: Prerelease
-        run: |
-          gh api \
-            "/repos/$GITHUB_REPOSITORY/releases/${{ fromJson(needs.create-draft-release.outputs.release).id }}" \
-            --method PATCH \
-            -H 'Accept: application/vnd.github+json' \
-            -H 'X-GitHub-Api-Version: 2022-11-28' \
-            -F draft=false \
-            -F prerelease=true
+            current_tag_name=$(
+              gh api \
+                "/repos/$GITHUB_REPOSITORY/releases/$release_id" \
+                -H 'Accept: application/vnd.github+json' \
+                -H 'X-GitHub-Api-Version: 2022-11-28' \
+                -q .tag_name
+            )
+            if [ "$current_tag_name" = $tag ]; then
+              exit
+            else
+              echo 'tag_name was not set. retrying' >&2
+            fi
+          done
+
+          echo "::error title=set-tag-name::Could not set 'tag_name'. Please set it manually"
+          exit 1
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
